#!/bin/bash

aws ecr get-login-password --region eu-north-1 --profile odin-cdk| docker login --username AWS --password-stdin 991049544436.dkr.ecr.eu-north-1.amazonaws.com

docker build -f Dockerfile.meso13 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso13 .
docker build -f Dockerfile.meso19 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso19 .
docker build -f Dockerfile.meso21 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso21 .
docker build -f Dockerfile.stnd1 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd1 .
docker build -f Dockerfile.stnd2 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd2 .
docker build -f Dockerfile.stnd8 -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd8 .

docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso13
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso19
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso21
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd1
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd2
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd8